export const bubbleSkills = [
    { src: "bootstrap-fill-svgrepo-com.svg", alt: "bootstrap" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "bootstrap-fill-svgrepo-com.svg", alt: "bootstrap" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "bootstrap-fill-svgrepo-com.svg", alt: "bootstrap" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "bootstrap-fill-svgrepo-com.svg", alt: "bootstrap" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "css-3-svgrepo-com.svg", alt: "css" },
    { src: "express-svgrepo-com.svg", alt: "express" },
    { src: "bootstrap-fill-svgrepo-com.svg", alt: "bootstrap" },
];
