import { Inter } from "next/font/google";
import "./globals.css";
import Contact from "./common/Contact";
import { HeaderLG, HeaderSmall } from "./common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="md:flex">
                    <div className="hidden md:block">
                        <HeaderLG />
                    </div>
                    <div className="sm:block md:hidden">
                        <HeaderSmall />
                    </div>
                    {children}
                    <Contact />
                </div>
            </body>
        </html>
    );
}
