import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Contact from "./common/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex">
                    <Header />
                    {children}
                    <Contact />
                </div>
            </body>
        </html>
    );
}
